#spring:

#Database
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/testdb?createDatabaseIfNotExist=true
#    username: username
#    password: password
    
          
 # jpa:
 #   hibernate:
 #     ddl-auto: create-drop
 #   show-sql: true
 #   database: postgresql
 #   database-platform: org.hibernate.dialect.PostgreSQLDialect

    
    